### PR TITLE
feat(webui): device discovery in cfm webui

### PR DESCRIPTION
**Pull request by Meng-20**
All discovered devices are added when cfm is initialized, but the user can discover new available devices without restarting the whole cfm by using the `Click to discover new devices` button on the dashboard page.

We prevent the user from manually adding blades to the CMA_Discovered_Blades appliance.

### CODE REVIEW

**Comment by scott-howe-1** [comment]
Don't forget to update the webui wiki with this new feature

**Comment by scott-howe-1** [comment]
Can we prevent the user from manually adding blades to the CMA_Discovered_Blades appliance.

**Comment by Meng-20** [comment]
> Don't forget to update the webui wiki with this new feature

Yes, will do in another task

**Review by scott-howe-1 — APPROVED** [review]

**Comment by Meng-20** [comment]
> Can we prevent the user from manually adding blades to the CMA_Discovered_Blades appliance.

I have added this, thanks

**Pull request merged**
