### PR TITLE
feat:  add a help page

### PR DESCRIPTION
**Pull request by Meng-20**
Added a help page to cfm-webui. The user can get the resources on how to use our product, trouble shottings and ask for help.
Here is the snapshot.
image

### CODE REVIEW

**Comment by scott-howe-1** [comment]
Can you put a snapshot of the help page in the PR description please, thanks.

**Comment by scott-howe-1** [comment]
2 things:
- As part of this PR, please add a placeholder "Troubleshooting" wiki page to the cfm wiki.  Just add "under construction" or something on that page for now.  Then, add that link to this PR (so the webui troubleshooting link goes to the new placeholder wiki page)
- Create a separate ticket for adding additional information to the wiki troubleshooting page.  Be sure to attach a link to the Errata document that Hongjian mentioned (for idea of things to add to the troubleshooting page).

Thanks.

**Comment by Meng-20** [comment]
> 2 things:
> 
> * As part of this PR, please add a placeholder "Troubleshooting" wiki page to the cfm wiki.  Just add "under construction" or something on that page for now.  Then, add that link to this PR (so the webui troubleshooting link goes to the new placeholder wiki page)
> * Create a separate ticket for adding additional information to the wiki troubleshooting page.  Be sure to attach a link to the Errata document that Hongjian mentioned (for idea of things to add to the troubleshooting page).
> 
> Thanks.

Thank you, Scott, I have updated my code, added a placeholder for the troubleshooting wiki page and created a new ticket to implement it. please check.

**Review by scott-howe-1 — APPROVED** [review]
Looks good.

Don't forget to modify your PR commit message format, when you merge, to include "feat:".

**Pull request merged**
