### PR TITLE
feat: add online\offline status to manager and datastore

### PR DESCRIPTION
**Pull request by scott-howe-1**
Implements the concept of a connection status between CFM and a blade\host (doesn't apply to an appliance yet) and stores that information within the datastore.  Currently, there are 3 states: "online", "offline" and "n/a".  The last one only applies to the appliance right now.  

The main intent here is to not have any "offline" devices be automatically deleted from the datastore.  This allows blade\host power cycling to occur without losing their information.  It also allows cfm-service to attempt to reconnect to these offline blades\host if it ever needs to restart.

While this tasks original intent was just to add the "status" to the datastore, the scope of the task expanded to include the manager layer as well.  To accurately update cfm-service about an individual devices connection status, it was easier to track\control the "status" in the manager layer and then just push it to the datastore when it was updated in manager.  This helped to keep the "status" state consistent between datastore and manager as well as allowed the manager to make runtime decisions based on the devices current connection status, without having to constantly reach into datastore.

This status is updated as requests are made to the CFM client.  Note that the connection status is determined solely by CFM making a request to the designated blade\host root redfish service: /redfish/v1.  If a response is received, it's online.  Otherwise, it's offline.

### CODE REVIEW

**Comment by Meng-20** [comment]
Thanks Scott, the cfm-service should be restarted if we want to update the connection status in the datastore, right?

**Comment by scott-howe-1** [comment]
> Thanks Scott, the cfm-service should be restarted if we want to update the connection status in the datastore, right?

No.  The status value in the datastore gets updated each time cfm tries to interact with a specific blade or host, regardless of whether or not that interaction occurs during cfm-service startup.

It is possible to restart cfm-service to force an update of the status, but that's not ideal.

Long-term, we do not want cfm-service to have to be constantly be restarted for the state to be maintained properly.   cfm-service  needs to handle the status variable in a way that is invisible to a webui\cli user.

**Comment by Meng-20** [comment]
> > Thanks Scott, the cfm-service should be restarted if we want to update the connection status in the datastore, right?
> 
> No. The status value in the datastore gets updated each time cfm tries to interact with a specific blade or host, regardless of whether or not that interaction occurs during cfm-service startup.
> 
> It is possible to restart cfm-service to force an update of the status, but that's not ideal.
> 
> Long-term, we do not want cfm-service to have to be constantly be restarted for the state to be maintained properly. cfm-service needs to handle the status variable in a way that is invisible to a webui\cli user.

Yes, you are right, but for a scenario, after I added a host, I shut down this device, in cfm-webui, the device disappeared, but the contents in cfmdatastore were not updated and also in cfm-service.

**Comment by scott-howe-1** [comment]
Have modified most of the client api "getters" to update the blade\host connection status.  The datastore "status" values is now being updated when you refresh the webui ui.  Have a look when you get a chance.

**Review by Meng-20 — APPROVED** [review]
Thank you, Scott, I tested your code and read the code, both good for me. Please don't forget to change active/inactive to online/offline in your description.

**Pull request merged**
